add_newline = true

format = """\
  $username\
  $directory\
  $kubernetes\
  $aws\
  $git_branch\
  $git_state\
  $git_status\
  $character\
  """

[character]
success_symbol = "\n[❯](bold green)"
error_symbol = "\n[✖](bold red)"

[cmd_duration]
min_time = 500

[directory]
truncation_length = 5
truncate_to_repo = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = false

[kubernetes]
symbol = "ﴱ "
format = 'on [ﴱ $context \($namespace\)](bold bright-green) '
disabled = false
[kubernetes.context_aliases]
"default" = "home-cluster"
 
[aws]
format = "on [$symbol$profile( $region)]($style) "
style = "bold Yellow"
symbol = "☁️ "
