[tools]
age = '1.1.1'             #renovate: packageName=FiloSottile/age
awscli = '2.15.8'        #renovate: datasource=github-tags packageName=aws/aws-cli versioning=^(?<version>)$
bat = '0.24.0'            #renovate: packageName=sharkdp/bat
chezmoi = '2.44.0'        #renovate: packageName=twpayne/chezmoi
cloudflared = '2024.1.1' #renovate: packageName=cloudflare/cloudflared
delta = '0.16.5'          #renovate: packageName=dandavison/delta
direnv = '2.33.0'         #renovate: packageName=direnv/direnv
fd = '9.0.0'              #renovate: packageName=sharkdp/fd
flux2 = '2.2.2'           #renovate: packageName=fluxcd/flux2
fzf = '0.39.0'            #renovate: packagename=junegunn/fzf
github-cli = '2.41.0'     #renovate: packageName=cli/cli
glow = '1.5.1'            #renovate: packageName=charmbracelet/glow
helm = '3.13.3'           #renovate: packageName=helm/helm
jq = '1.7'                #renovate: packageName=jqlang/jq
k9s = '0.31.2'            #renovate: packageName=derailed/k9s
krew = '0.4.4'            #renovate: packageName=kubernetes-sigs/krew
kubectl = '1.26.3'        #renovate: datasource=github-tags packageName=kubernetes/kubectl versioning=^kubernetes-(?<version>.*)$
kustomize = '5.0.1'       #renovate: packageName=kubernetes-sigs/kustomize
lazygit = '0.40.2'        #renovate: packageName=jesseduffield/lazygit
neovim = '0.9.5'          #renovate: packageName=neovim/neovim
nodejs = '21.5.0'         #renovate: packageName=nodejs/node
pnpm = '8.14.1'           #renovate: packageName=pnpm/pnpm
pre-commit = '3.6.0'      #renovate: packageName=pre-commit/pre-commit
ripgrep = '14.1.0'        #renovate: packageName=BurntSushi/ripgrep
rust = '1.75.0'           #renovate: packageName=rust-lang/rust
sops = '3.8.1'            #renovate: packageName=mozilla/sops
stern = '1.28.0'          #renovate: packageName=stern/stern
talhelper = '1.16.5'      #renovate: packageName=budimanjojo/talhelper
talosctl = '1.6.1'        #renovate: packageName=siderolabs/talos
task = '3.33.1'           #renovate: packageName=go-task/task
yq = '4.40.5'             #renovate: packageName=mikefarah/yq

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true # enabled by default (different than asdf)

# configure `rtx install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

verbose = false     # set to true to see full installation output, see `RTX_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr

experimental = true # enable experimental features
log_level = 'info'  # log verbosity, see `RTX_LOG_LEVEL`
